{% set name = "charidotella" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/charidotella-{{ version }}.tar.gz
  sha256: 1e85334280d7d9671f0b4b5c99e4a5d185180d441e3f169c64d8a0de279eff77
  patches:
    - unvendor_command_line_tools.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - command_line_tools
    - aedat
    - colourtime
    - coolname
    - event-stream
    - jsonschema
    - matplotlib-base
    - pillow >=9.1
    - scipy
    - toml

test:
  imports:
    - charidotella
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/neuromorphicsystems/charidotella
  summary: Charidotella is a toolbox to organise and visualise Event Stream (.es) recordings
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
